spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  liquibase:
    change-log: db/changelog/changelog-head.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
  hibernate:
      ddl-auto: validate